const Constants = {
    //Game constants
    FETCH_GAMES: "FETCH_GAMES",
    RECEIVED_GAMES: "RECEIVED_GAMES",
    GAMES_CHANGED: "GAMES_CHANGED",
    FETCH_GAMES_ERROR: "FETCH_GAMES_ERROR",

    // User constants
    FETCH_USER: "FETCH_USER",
    RECEIVED_USER: "RECEIVED_USER",
    USER_CHANGED: "USER_CHANGED",
    FETCH_USER_ERROR: "FETCH_USER_ERROR",

    // Friend constants
    FETCH_FRIENDS: "FETCH_FRIENDS",
    RECEIVED_FRIENDS: "RECEIVED_FRIENDS",
    FRIENDS_CHANGED: "FRIENDS_CHANGED",
    FETCH_FRIENDS_ERROR: "FETCH_FRIENDS_ERROR",

};

export default GameConstants;
